### ISSUE TITLE
Can't create world.

### ISSUE THREAD

**Issue by Ibirtem** [wildcardgamez/BuddyCards#32] opened 2021-09-07 12:45 UTC
A screen with the launch of the world with "Safe Mode" is displayed. When pressed, nothing happens. It will be difficult to say exactly which mod conflicts with the Cards, because there are almost a hundred mods. Xd

Debug - https://gist.github.com/Ibirtem/bb61657bf1d8dd23f486c846faec3a8a
1.16.5 Forge 36.2.4

**Comment by wildcardgamez** [comment] 2021-09-12 03:15
I'm sorry, but I don't see any issues that make me think this is BuddyCards at all. In fact, I can't even see where an issue is caused. When looking through it though, the only issues with buddycards seem to be the ones I expect, which are due to how aquaculture deals with integration. None of this makes me think it's causing this, and even if it was, I no longer support 1.16.5 versions. If this is still an issue in 1.17 and is caused by my mod, I'll look into it, but all you've given me is a debug with no info I could use and the explanation which doesn't help me much. If what you mean by safe mode is the experimental world settings, that's completely normal for most forge modpacks.

Because of the fact I have no clue what the issue is and this is for an unsupported version, I'm going to close it.

**Closed by wildcardgamez** 2021-09-12 03:15 UTC
